### ISSUE TITLE
Amazon links don't always load

### ISSUE THREAD

**Issue by raiyni** [Wingysam/Christmas-Community#91]
Looked in docker compose logs and saw nothing. I have no other information other than I added several amazon  items with their short url without the affiliate params.

![image](https://github.com/Wingysam/Christmas-Community/assets/22979513/bf7f136a-45e6-40cb-9e7c-c8b0bf5c503c)

docker-compose:
```yaml
version: "3"
services:
  christmas-community:
    image: wingysam/christmas-community
    volumes:
      - ./data:/data
    environment:
      SITE_TITLE: 'Wish Lists'
      SMILE: 'false'
      MARKDOWN: 'true'
      LISTS_PUBLIC: 'true'
      GUEST_PASSWORD: 'xxxx'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wishlist.rule=Host(`xxx`)"
      - "traefik.http.routers.wishlist.entrypoints=xxx"
      - "traefik.http.routers.wishlist.tls.certresolver=xxx"
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
```
